# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Faf's lair
email: fribes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog regroupant mes centres d'intérets afin de les partager
  avec mes amis et au-delà. De la moto, de la plongée, de la zététique, 
  du surf, des états d'âmes -le moins possible- et tout ce qui me passera par la
  tête ;-)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fribes.github.io" # the base hostname & protocol for your site
twitter_username: leFribes
github_username:  fribes

# Build settings
markdown: kramdown
